executor: parallel

tasks:
  - source: tasks/get-historical.py
    name: get
    product:
      nb: products/get-historical.ipynb
      data: products/historical.csv
    params:
      path_to_data: '{{here}}/raw.csv'

  - source: tasks/visualize.py
    product: products/visualize.ipynb
  
  - source: tasks/clean.py
    product:
        nb: products/clean.ipynb
        data: products/clean.csv
    params:
      training: true
    on_finish: tests.quality.clean

  - source: tasks/fit.py
    product:
        nb: products/fit.ipynb
        model: products/model.pkl
        x_train: products/x_train.pkl
        y_train: products/y_train.pkl
        x_test: products/x_test.pkl
        y_test: products/y_test.pkl
        y_pred: products/y_pred.pkl
        y_pred_quant: products/y_pred_quant.pkl
        data: products/data.pkl

  - source: tasks/evaluate.py
    product: products/evaluate.ipynb