name: CI
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          eval "$(conda shell.bash hook)"
          conda env create --file environment.yml --name env
      # order is important here: unit tests should be fast. If they fail,
      # there's no need to run the pipeline
      - name: Run unit tests
        run: pytest
      - name: Run pipeline
        run: |
          eval "$(conda shell.bash hook)"
          conda activate env
          ploomber build